# -*- coding: utf-8 -*-
"""data_preprocessing.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eDpKKQoeXuWJ-XjcKMw8tMgkjZjLZC4J
"""

import pandas as pd
import numpy as np
df = pd.read_csv("data.csv")

df.head()
df.info()

# Check dataset shape
print("Dataset shape:", df.shape)

# Preview first 5 rows
print(df.head())

# Check missing values
print(df.isnull().sum())

df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
print(df.columns)

df = df.rename(columns={
    'customerid': 'customer_id',
    'productid': 'product_id',
    'transactiondate': 'transaction_date',
    'paymentmethod': 'payment_method',
    'storelocation': 'store_location',
    'productcategory': 'product_category',
    'discountapplied(%)': 'discount',
    'totalamount': 'total_amount'
})

import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10,5))
sns.boxplot(x=df['total_amount'])
plt.title("Outliers in Total Amount")
plt.show()

"""Detect Outliers"""

#Using IQR method
Q1 = df['total_amount'].quantile(0.25)
Q3 = df['total_amount'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

print(lower_bound, upper_bound)

df = df[(df['total_amount'] >= lower_bound) &
        (df['total_amount'] <= upper_bound)]
#Apply to other columns
cols = ['quantity', 'price', 'total_amount']

for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower) & (df[col] <= upper)]

#Outliers
print(df.shape)

# Ensure date format
df['transaction_date'] = pd.to_datetime(df['transaction_date'])

# Create reference date
today = df['transaction_date'].max() + pd.Timedelta(days=1)

# Create RFM table
rfm = df.groupby('customer_id').agg({
    'transaction_date': lambda x: (today - x.max()).days,
    'customer_id': 'count',
    'total_amount': 'sum'
})

# Rename columns
rfm.columns = ['recency', 'frequency', 'monetary']
rfm.reset_index(inplace=True)

print(rfm.head())

rfm['avg_spend'] = df.groupby('customer_id')['total_amount'].mean().values
rfm['discount_usage'] = df.groupby('customer_id')['discount'].mean().values
rfm['category_count'] = df.groupby('customer_id')['product_category'].nunique().values
features = rfm[['recency', 'frequency', 'monetary',
                'avg_spend', 'discount_usage', 'category_count']]

df.to_csv("processed_data.csv", index=False)

import os
print(os.listdir())

from google.colab import files
files.download("processed_data.csv")