# -*- coding: utf-8 -*-
"""feature_engineering.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1l4DQL0wwypcXTqOPCjw2cjKXKlBHEOPO
"""

import pandas as pd

df = pd.read_csv("processed_data.csv", engine='python', on_bad_lines='skip')
print(df.shape)
df.head()

# Numerical summary
display(df.describe())

# Categorical summary
cat_cols = df.select_dtypes(include='object').columns
for col in cat_cols:
    print(f"\nColumn: {col}")
    print(df[col].value_counts())

## 4️⃣ Check for missing values
print("Missing values per column:")
print(df.isnull().sum())

df = df.dropna()
print("New dataset shape:", df.shape)

df = pd.read_csv("processed_data.csv")
df['transaction_date'] = pd.to_datetime(df['transaction_date'], dayfirst=True)

import datetime as dt

# Define snapshot date (today or one day after last transaction)
snapshot_date = df['transaction_date'].max() + pd.Timedelta(days=1)

# Aggregate by customer
rfm = df.groupby('customer_id').agg({
    'transaction_date': lambda x: (snapshot_date - x.max()).days,  # Recency
    'product_id': 'count',                                          # Frequency
    'total_amount': 'sum'                                           # Monetary
}).reset_index()

rfm.rename(columns={
    'transaction_date': 'Recency',
    'product_id': 'Frequency',
    'total_amount': 'Monetary'
}, inplace=True)

rfm.head()

# Recency: lower = better
rfm['R_Score'] = pd.qcut(rfm['Recency'], 4, labels=[4,3,2,1])

# Frequency & Monetary: rank, then scale 1-4
rfm['F_Score'] = pd.qcut(rfm['Frequency'].rank(method='first'), 4, labels=[1,2,3,4])
rfm['M_Score'] = pd.qcut(rfm['Monetary'].rank(method='first'), 4, labels=[1,2,3,4])

# Combine to get RFM Segment and total score
rfm['RFM_Segment'] = rfm['R_Score'].astype(str) + rfm['F_Score'].astype(str) + rfm['M_Score'].astype(str)
rfm['RFM_Score'] = rfm[['R_Score','F_Score','M_Score']].sum(axis=1).astype(int)

# Preview
rfm.head()

rfm.to_csv("rfm_table.csv", index=False)